### ISSUE TITLE
Massive lagspikes, time dialation issues

### ISSUE THREAD

**Issue by ForrestWick** [Citadel-Station-13/Citadel-Station-13#9671]
## Round ID: no specific IDs, its been going on for a while, roughly a couple weeks.

Issue in question is that at seemingly random times, we'll have all of or most of the server completely freeze up or lag. It seems to be occurring primarily during the 30 minute mark of a round, if not before that.

Steps taken to try fixing it client side have been:
Disabling firewalls/white listing beyond and dreamseeker in antivirus
Closing all programs but beyond via task manager
Rebooting the game window
Rebooting beyond
Computer reset
Trying different internet connections
Cache and cookie clearing
Adjusting power settings

Nothing seems to work. When asked about it a week ago, staff said the server itself seemed fine. MIGHT be a code issue

**Comment by Arturlang** [comment]
Its most likely to all those runtimes that happen and we can't fix due to not being able to see them

**Comment by Ghommie** [comment]
I could say this is an issue with the server and not the repo and as thus should be closed. But there are actually a couple few coded things at the least that actually cause server-wide lag spikes or time dilatation, such as jukeboxes which should be getting fixed in #10119.
This a very broad issue report though and doesn't provide many details on the possible causes, not blaming you of anything... :pensive:
